name: Destroy Resources

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "yes" to confirm resource destruction'
        required: true
        default: 'no'

jobs:
  validate-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (Destroy)
        id: plan
        run: terraform plan -destroy -out=destroy.plan

      - name: List Resources to be Destroyed
        id: validate
        run: terraform show -json destroy.plan | jq '.resource_changes[] | select(.change.actions | contains(["delete"])) | .address'

      - name: Save plan output
        uses: actions/upload-artifact@v2
        with:
          name: destroy-plan
          path: destroy.plan

  destroy-resources:
    runs-on: ubuntu-latest
    needs: validate-resources
    if: ${{ github.event.inputs.confirm_destroy == 'yes' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Download plan
        uses: actions/download-artifact@v2
        with:
          name: destroy-plan
          path: .

      - name: Terraform Destroy
        run: terraform apply destroy.plan

